// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cokhot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250519201712_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("IdIngredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIngredient"));

                    b.Property<string>("NomIngredient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrixKiloIngredient")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdIngredient");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("IngredientDansPlat", b =>
                {
                    b.Property<int>("IdPlat")
                        .HasColumnType("int");

                    b.Property<int>("IdIngredient")
                        .HasColumnType("int");

                    b.Property<int>("IngredientIdIngredient")
                        .HasColumnType("int");

                    b.Property<int>("PlatIdPlat")
                        .HasColumnType("int");

                    b.Property<string>("QuantiteIngredient")
                        .HasColumnType("longtext");

                    b.HasKey("IdPlat", "IdIngredient");

                    b.HasIndex("IngredientIdIngredient");

                    b.HasIndex("PlatIdPlat");

                    b.ToTable("IngredientsDansPlat");
                });

            modelBuilder.Entity("Plat", b =>
                {
                    b.Property<int>("IdPlat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlat"));

                    b.Property<bool>("estEpicePlat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("estHealthy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("estVegetarien")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lienPhotoPlat")
                        .HasColumnType("longtext");

                    b.Property<string>("lienRecettePlat")
                        .HasColumnType("longtext");

                    b.Property<string>("nomPlat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("notePlat")
                        .HasColumnType("int");

                    b.Property<string>("originePlat")
                        .HasColumnType("longtext");

                    b.Property<string>("repasPlat")
                        .HasColumnType("longtext");

                    b.Property<string>("saveurPlat")
                        .HasColumnType("longtext");

                    b.Property<int?>("tempsPreparationPlat")
                        .HasColumnType("int");

                    b.HasKey("IdPlat");

                    b.ToTable("Plats");

                    b.HasData(
                        new
                        {
                            IdPlat = 1,
                            estEpicePlat = false,
                            estHealthy = true,
                            estVegetarien = false,
                            lienPhotoPlat = "",
                            lienRecettePlat = "",
                            nomPlat = "Spaghetti Bolognese",
                            notePlat = 5,
                            originePlat = "Italie",
                            repasPlat = "Dîner",
                            saveurPlat = "Savoureux",
                            tempsPreparationPlat = 30
                        },
                        new
                        {
                            IdPlat = 2,
                            estEpicePlat = false,
                            estHealthy = true,
                            estVegetarien = false,
                            lienPhotoPlat = "",
                            lienRecettePlat = "",
                            nomPlat = "Salade César",
                            notePlat = 4,
                            originePlat = "États-Unis",
                            repasPlat = "Déjeuner",
                            saveurPlat = "Frais",
                            tempsPreparationPlat = 15
                        });
                });

            modelBuilder.Entity("IngredientDansPlat", b =>
                {
                    b.HasOne("Ingredient", "Ingredient")
                        .WithMany("IngredientsDansPlat")
                        .HasForeignKey("IngredientIdIngredient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plat", "Plat")
                        .WithMany("IngredientsDansPlat")
                        .HasForeignKey("PlatIdPlat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Plat");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Navigation("IngredientsDansPlat");
                });

            modelBuilder.Entity("Plat", b =>
                {
                    b.Navigation("IngredientsDansPlat");
                });
#pragma warning restore 612, 618
        }
    }
}
